site_name: Geodistpy
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
repo_url: https://github.com/pawangeek/geodistpy
repo_name: pawangeek/geodistpy
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pawangeek
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/in/pawan-jain
plugins:
  - search
  - mkdocstrings
nav:
  - Index: index.md
  - Getting-started: getting-started.md
  - API References: api-reference.md
  - Explanation: explanation.md